/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackTrackIdRouteImport } from './routes/track/$trackId'
import { Route as FilesSplatRouteImport } from './routes/files/$'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as AuthedUploadRouteImport } from './routes/_authed/upload'
import { Route as AuthedMyTracksRouteImport } from './routes/_authed/my-tracks'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminErrorsRouteImport } from './routes/api/admin/errors'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTrackIdRoute = TrackTrackIdRouteImport.update({
  id: '/track/$trackId',
  path: '/track/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesSplatRoute = FilesSplatRouteImport.update({
  id: '/files/$',
  path: '/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUploadRoute = AuthedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMyTracksRoute = AuthedMyTracksRouteImport.update({
  id: '/my-tracks',
  path: '/my-tracks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminErrorsRoute = ApiAdminErrorsRouteImport.update({
  id: '/api/admin/errors',
  path: '/api/admin/errors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthedAdminRoute
  '/my-tracks': typeof AuthedMyTracksRoute
  '/upload': typeof AuthedUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/files/$': typeof FilesSplatRoute
  '/track/$trackId': typeof TrackTrackIdRoute
  '/api/admin/errors': typeof ApiAdminErrorsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthedAdminRoute
  '/my-tracks': typeof AuthedMyTracksRoute
  '/upload': typeof AuthedUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/files/$': typeof FilesSplatRoute
  '/track/$trackId': typeof TrackTrackIdRoute
  '/api/admin/errors': typeof ApiAdminErrorsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/admin': typeof AuthedAdminRoute
  '/_authed/my-tracks': typeof AuthedMyTracksRoute
  '/_authed/upload': typeof AuthedUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/files/$': typeof FilesSplatRoute
  '/track/$trackId': typeof TrackTrackIdRoute
  '/api/admin/errors': typeof ApiAdminErrorsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/login'
    | '/signup'
    | '/admin'
    | '/my-tracks'
    | '/upload'
    | '/api/upload'
    | '/files/$'
    | '/track/$trackId'
    | '/api/admin/errors'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/signup'
    | '/admin'
    | '/my-tracks'
    | '/upload'
    | '/api/upload'
    | '/files/$'
    | '/track/$trackId'
    | '/api/admin/errors'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/health'
    | '/login'
    | '/signup'
    | '/_authed/admin'
    | '/_authed/my-tracks'
    | '/_authed/upload'
    | '/api/upload'
    | '/files/$'
    | '/track/$trackId'
    | '/api/admin/errors'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiUploadRoute: typeof ApiUploadRoute
  FilesSplatRoute: typeof FilesSplatRoute
  TrackTrackIdRoute: typeof TrackTrackIdRoute
  ApiAdminErrorsRoute: typeof ApiAdminErrorsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$trackId': {
      id: '/track/$trackId'
      path: '/track/$trackId'
      fullPath: '/track/$trackId'
      preLoaderRoute: typeof TrackTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/$': {
      id: '/files/$'
      path: '/files/$'
      fullPath: '/files/$'
      preLoaderRoute: typeof FilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/upload': {
      id: '/_authed/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthedUploadRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/my-tracks': {
      id: '/_authed/my-tracks'
      path: '/my-tracks'
      fullPath: '/my-tracks'
      preLoaderRoute: typeof AuthedMyTracksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/errors': {
      id: '/api/admin/errors'
      path: '/api/admin/errors'
      fullPath: '/api/admin/errors'
      preLoaderRoute: typeof ApiAdminErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRoute
  AuthedMyTracksRoute: typeof AuthedMyTracksRoute
  AuthedUploadRoute: typeof AuthedUploadRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedMyTracksRoute: AuthedMyTracksRoute,
  AuthedUploadRoute: AuthedUploadRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiUploadRoute: ApiUploadRoute,
  FilesSplatRoute: FilesSplatRoute,
  TrackTrackIdRoute: TrackTrackIdRoute,
  ApiAdminErrorsRoute: ApiAdminErrorsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
