/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilesSplatRouteImport } from './routes/files/$'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as LayoutSignupRouteImport } from './routes/_layout/signup'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as LayoutAuthedRouteImport } from './routes/_layout/_authed'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminErrorsRouteImport } from './routes/api/admin/errors'
import { Route as LayoutAuthedUploadRouteImport } from './routes/_layout/_authed/upload'
import { Route as LayoutAuthedMyTracksRouteImport } from './routes/_layout/_authed/my-tracks'
import { Route as LayoutAuthedAdminRouteImport } from './routes/_layout/_authed/admin'
import { Route as LayoutAuthedAccountRouteImport } from './routes/_layout/_authed/account'
import { Route as LayoutTrackTrackIdIndexRouteImport } from './routes/_layout/track.$trackId/index'
import { Route as LayoutTrackTrackIdEditRouteImport } from './routes/_layout/track.$trackId/edit'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesSplatRoute = FilesSplatRouteImport.update({
  id: '/files/$',
  path: '/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSignupRoute = LayoutSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthedRoute = LayoutAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminErrorsRoute = ApiAdminErrorsRouteImport.update({
  id: '/api/admin/errors',
  path: '/api/admin/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthedUploadRoute = LayoutAuthedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => LayoutAuthedRoute,
} as any)
const LayoutAuthedMyTracksRoute = LayoutAuthedMyTracksRouteImport.update({
  id: '/my-tracks',
  path: '/my-tracks',
  getParentRoute: () => LayoutAuthedRoute,
} as any)
const LayoutAuthedAdminRoute = LayoutAuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutAuthedRoute,
} as any)
const LayoutAuthedAccountRoute = LayoutAuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => LayoutAuthedRoute,
} as any)
const LayoutTrackTrackIdIndexRoute = LayoutTrackTrackIdIndexRouteImport.update({
  id: '/track/$trackId/',
  path: '/track/$trackId/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTrackTrackIdEditRoute = LayoutTrackTrackIdEditRouteImport.update({
  id: '/track/$trackId/edit',
  path: '/track/$trackId/edit',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LayoutLoginRoute
  '/signup': typeof LayoutSignupRoute
  '/api/upload': typeof ApiUploadRoute
  '/files/$': typeof FilesSplatRoute
  '/account': typeof LayoutAuthedAccountRoute
  '/admin': typeof LayoutAuthedAdminRoute
  '/my-tracks': typeof LayoutAuthedMyTracksRoute
  '/upload': typeof LayoutAuthedUploadRoute
  '/api/admin/errors': typeof ApiAdminErrorsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/track/$trackId/edit': typeof LayoutTrackTrackIdEditRoute
  '/track/$trackId': typeof LayoutTrackTrackIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LayoutLoginRoute
  '/signup': typeof LayoutSignupRoute
  '/api/upload': typeof ApiUploadRoute
  '/files/$': typeof FilesSplatRoute
  '/account': typeof LayoutAuthedAccountRoute
  '/admin': typeof LayoutAuthedAdminRoute
  '/my-tracks': typeof LayoutAuthedMyTracksRoute
  '/upload': typeof LayoutAuthedUploadRoute
  '/api/admin/errors': typeof ApiAdminErrorsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/track/$trackId/edit': typeof LayoutTrackTrackIdEditRoute
  '/track/$trackId': typeof LayoutTrackTrackIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/health': typeof HealthRoute
  '/_layout/_authed': typeof LayoutAuthedRouteWithChildren
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/signup': typeof LayoutSignupRoute
  '/api/upload': typeof ApiUploadRoute
  '/files/$': typeof FilesSplatRoute
  '/_layout/_authed/account': typeof LayoutAuthedAccountRoute
  '/_layout/_authed/admin': typeof LayoutAuthedAdminRoute
  '/_layout/_authed/my-tracks': typeof LayoutAuthedMyTracksRoute
  '/_layout/_authed/upload': typeof LayoutAuthedUploadRoute
  '/api/admin/errors': typeof ApiAdminErrorsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_layout/track/$trackId/edit': typeof LayoutTrackTrackIdEditRoute
  '/_layout/track/$trackId/': typeof LayoutTrackTrackIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/login'
    | '/signup'
    | '/api/upload'
    | '/files/$'
    | '/account'
    | '/admin'
    | '/my-tracks'
    | '/upload'
    | '/api/admin/errors'
    | '/api/auth/$'
    | '/track/$trackId/edit'
    | '/track/$trackId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/signup'
    | '/api/upload'
    | '/files/$'
    | '/account'
    | '/admin'
    | '/my-tracks'
    | '/upload'
    | '/api/admin/errors'
    | '/api/auth/$'
    | '/track/$trackId/edit'
    | '/track/$trackId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/health'
    | '/_layout/_authed'
    | '/_layout/login'
    | '/_layout/signup'
    | '/api/upload'
    | '/files/$'
    | '/_layout/_authed/account'
    | '/_layout/_authed/admin'
    | '/_layout/_authed/my-tracks'
    | '/_layout/_authed/upload'
    | '/api/admin/errors'
    | '/api/auth/$'
    | '/_layout/track/$trackId/edit'
    | '/_layout/track/$trackId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  HealthRoute: typeof HealthRoute
  ApiUploadRoute: typeof ApiUploadRoute
  FilesSplatRoute: typeof FilesSplatRoute
  ApiAdminErrorsRoute: typeof ApiAdminErrorsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/$': {
      id: '/files/$'
      path: '/files/$'
      fullPath: '/files/$'
      preLoaderRoute: typeof FilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/signup': {
      id: '/_layout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LayoutSignupRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authed': {
      id: '/_layout/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/errors': {
      id: '/api/admin/errors'
      path: '/api/admin/errors'
      fullPath: '/api/admin/errors'
      preLoaderRoute: typeof ApiAdminErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authed/upload': {
      id: '/_layout/_authed/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof LayoutAuthedUploadRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_layout/_authed/my-tracks': {
      id: '/_layout/_authed/my-tracks'
      path: '/my-tracks'
      fullPath: '/my-tracks'
      preLoaderRoute: typeof LayoutAuthedMyTracksRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_layout/_authed/admin': {
      id: '/_layout/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAuthedAdminRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_layout/_authed/account': {
      id: '/_layout/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof LayoutAuthedAccountRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_layout/track/$trackId/': {
      id: '/_layout/track/$trackId/'
      path: '/track/$trackId'
      fullPath: '/track/$trackId'
      preLoaderRoute: typeof LayoutTrackTrackIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/track/$trackId/edit': {
      id: '/_layout/track/$trackId/edit'
      path: '/track/$trackId/edit'
      fullPath: '/track/$trackId/edit'
      preLoaderRoute: typeof LayoutTrackTrackIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutAuthedRouteChildren {
  LayoutAuthedAccountRoute: typeof LayoutAuthedAccountRoute
  LayoutAuthedAdminRoute: typeof LayoutAuthedAdminRoute
  LayoutAuthedMyTracksRoute: typeof LayoutAuthedMyTracksRoute
  LayoutAuthedUploadRoute: typeof LayoutAuthedUploadRoute
}

const LayoutAuthedRouteChildren: LayoutAuthedRouteChildren = {
  LayoutAuthedAccountRoute: LayoutAuthedAccountRoute,
  LayoutAuthedAdminRoute: LayoutAuthedAdminRoute,
  LayoutAuthedMyTracksRoute: LayoutAuthedMyTracksRoute,
  LayoutAuthedUploadRoute: LayoutAuthedUploadRoute,
}

const LayoutAuthedRouteWithChildren = LayoutAuthedRoute._addFileChildren(
  LayoutAuthedRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAuthedRoute: typeof LayoutAuthedRouteWithChildren
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutSignupRoute: typeof LayoutSignupRoute
  LayoutTrackTrackIdEditRoute: typeof LayoutTrackTrackIdEditRoute
  LayoutTrackTrackIdIndexRoute: typeof LayoutTrackTrackIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthedRoute: LayoutAuthedRouteWithChildren,
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutSignupRoute: LayoutSignupRoute,
  LayoutTrackTrackIdEditRoute: LayoutTrackTrackIdEditRoute,
  LayoutTrackTrackIdIndexRoute: LayoutTrackTrackIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  HealthRoute: HealthRoute,
  ApiUploadRoute: ApiUploadRoute,
  FilesSplatRoute: FilesSplatRoute,
  ApiAdminErrorsRoute: ApiAdminErrorsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
